// AUTO-GENERATED by scripts/build-bio.mjs from content/bio.md.
// Edit the markdown file, not this file.

export type Segment = { text: string; href?: string };
export type Paragraph = Segment[];

export const HERO_NAME = "Marco Sevilla";

export const PARAGRAPHS: Paragraph[] = [
  [
    { text: "I'm a Product Designer in San Francisco. Currently at" },
    { text: "Canary Technologies", href: "https://www.canarytechnologies.com/" },
    { text: ", building software for the world's largest hospitality brands including Marriott, Wyndham, Best Western, and IHG. I lead design for our Food & Beverage, Upsells, Guest Experience, and Tipping products." },
  ],
  [
    { text: "Growing up, I spent countless hours on PCs my dad custom-built, editing videos, manipulating photos, and creating worlds in simulation games. Those digital playgrounds turned into a love for honing my craft, and a deep interest in building systems that help people do their best work." },
  ],
  [
    { text: "Previously, I helped democratize wine discovery at" },
    { text: "Vivino", href: "https://www.vivino.com/" },
    { text: ", made animated video production more accessible at" },
    { text: "Vyond", href: "https://www.vyond.com/" },
    { text: ", and built an all-in-one productivity tool for software engineers at" },
    { text: "General Task", href: "https://www.generaltask.com/" },
    { text: "." },
  ],
  [
    { text: "When I'm not designing, you'll find me shooting" },
    { text: "music photography", href: "photo-stack" },
    { text: ", working on creative side projects, singing, or on the pickleball court." },
  ],
];
