// AUTO-GENERATED by scripts/build-bio.mjs from content/bio.md.
// Edit the markdown file, not this file.

export type Segment = { text: string; href?: string };
export type Paragraph = Segment[];

export const HERO_NAME = "Marco Sevilla";

export const PARAGRAPHS: Paragraph[] = [
  [
    { text: "I was born and raised in the San Francisco Bay Area. My work blends a life-long enthusiasm for technology, a love of visual craft, and a keen interest in human psychology. I think of myself as a creative generalist. I'm always eager to try new things, throw things at the wall, and find connections between seemingly disparate things." },
  ],
  [
    { text: "I discovered software as a creative medium early. As a kid, I spent countless hours on PCs my dad custom-built. These were the digital playgrounds that shaped my love for creating. Between simulation games, Windows Movie Maker, and Adobe Flash, designing software ended up feeling like the natural path." },
  ],
  [
    { text: "Since then, I've collaborated with the" },
    { text: "world's largest hotel enterprises", href: "https://www.canarytechnologies.com/" },
    { text: "on software used by millions of guests, built an" },
    { text: "all-in-one productivity tool", href: "https://www.generaltask.com/" },
    { text: "for software engineers, helped" },
    { text: "democratize wine shopping", href: "https://www.vivino.com/" },
    { text: ", and worked to make" },
    { text: "animated video production", href: "https://www.vyond.com/" },
    { text: "accessible to anyone." },
  ],
  [
    { text: "Ultimately, my goal is to continuously improve my craft and build equally useful and beautiful products that improve people's lives. Thanks for checking out my website!" },
  ],
];
